site_name: BurningMyself
site_description: .net,java,php,python,docker,web
site_author: BurningMyself
site_url: https://burningmyself.github.io
# site_favicon: favicon.ico
copyright: BurningMyself<a href='https://beian.miit.gov.cn/' target='_blank'>  蜀ICP备15033200号-1</a>
site_url: https://burningmyself.gitee.io
repo_name: 'burningmyself.github.io'
repo_url: 'https://github.com/burningmyself/burningmyself.github.io'

theme:
    name: material
    highlightjs: true
    favicon: favicon.ico
    language: 'zh'
    feature:
        tabs: false
    hljs_languages:
        - yaml
        - rust
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s    
           
nav: 
  - 介绍: index.md 
  - 技术博文: 
    - .NET: 
        - C#新特性语法: net/c_sharp.md
        - .Net Core Docker 部署: net/c_docker.md
        - Docker 容器化部署 ASP.NET Core: net/c_sqlserver_nginx.md
        - 让你的ASP.NET Core应用程序更安全: net/c_core_safety.md
        - ASP.NET Core开发者指南: net/c_core_study_route.md
    - Java: 
        - Java特性: java/feature.md 
        - Java类加载: java/load-class.md
        - Orm的优缺点: java/orm.md
        - BIO与NIO: java/bio-nio.md
        - RocketMq下载与安装: java/rocketmq/rmq-1.md
        - Spring常用注解: java/springAnnotation.md
        - Java 虚拟机: java/javavm.md
        - Spring 常用设计: java/springdesign.md
        - Spring Cloud: java/spring-cloud.md
        - Java simple: java/java-simple.md
        - Java Validator: java/java-validator.md
        - Java String: java/java-string.md
        - Java Utils: java/java-utils.md
    - Python: 
        - Python特性: python/feature.md 
        - Python字符拼接: python/str_joint.md
        - Python语法技巧: python/syntax_rule.md
        - 远程部署神器 Fabric: python/fabric.md
    - Go:
        - Go基础语法: go/go_base.md
    - PHP: 
        - 框架: php/kj.md    
    - Web:
        - es6语法: web/es6.md
        - 阿里js样式规范: web/ali_js_style.md
        - node.js文档: web/node.js.md
        - React 开发者指南: web/react.md
        - Dart语法学习: dart/syntax.md
        - React 面试: web/react_interview.md
        - js 工具函数: web/js_tool_method.md
        - vue与react比较: web/vue_cp_react.md
        - JavaScript 基础: web/javascript.md
    - SQL:
        - MySQL优化: sql/mysql_yh.md
        - MySQL优化: sql/mysql_yh17.md
        - MySQL日志: sql/mysql_log.md
        - MySQL索引: sql/mysql_index.md
        - MySQL PXC集群: sql/mysql_pxc.md
        - MySQL 数据库应用: sql/mysql_use.md
        - MySql 备份: sql/mysql_backups.md
        - Sql Server 主从备份: sql/sql_server_master.md
        - 数据库之互联网常用分库分表方案: sql/data_split.md
        - Mybatis使用心德: sql/mybatis.md
    - Linux: 
        - Linux学习笔记: linux/linux.md
        - 常用命令: linux/often.md
        - 实用的Linux 命令: linux/ope.md        
    - Docker: 
        - Docker全科: docker/docker.md
        - docker和docker-compose配置常用环境: docker/docker-compose.md   
        - Docker部署Jenkins: docker/docker-jenkins.md 
        - Docker部署Phabricator: docker/docker-phabricator.md
    - Tool: 
        - Git: tool/git.md
        - Git动画展示: tool/gitusual.md
        - Git问题处理: tool/gitquestion.md
        - GitFlow: tool/gitflow.md
        - GitBook: tool/gitbook.md
        - Git提交日志规范: tool/gitcmr.md
        - Markdown: tool/markdown.md
        - CI/CD: tool/cicd.md
        - mkdocs简单使用: tool/mkdocs.md
        - Git的黑魔法: tool/gitstudy.md
        - MinIO 搭建使用: tool/minio.md
        - Cat分布式监控: tool/cat-monitoring.md
  - 云架构:
    - 云原生: cloud/native.md
    - 虚拟化技术: cloud/virtual.md
    - 云计算: cloud/compute.md
    - 应用部署容器化演进: cloud/apprelease.md
    - 容器技术所涉及Linux内核关键技术: cloud/containerlinux.md
    - Docker:
      - 容器管理工具Docker生态架构及部署: cloud/docker/docker_native.md
      - 使用容器运行Nginx应用及Docker命令: cloud/docker/docker_nginx.md
      - Docker容器镜像: cloud/docker/docker_image.md
      - Docker容器镜像加速器及本地容器镜像仓库: cloud/docker/docker_image_fast.md
      - Docker容器化部署企业级应用集群: cloud/docker/docker_container_enterprice.md
      - Dockerfile精讲及新型容器镜像构建技术: cloud/docker/docker_file.md
      - Docker容器网络与通信原理深度解析: cloud/docker/docker_network.md
      - Docker容器数据持久化存储机制: cloud/docker/docker_date.md
      - Docker容器服务编排利器Docker Compose应用实战: cloud/docker/docker_compose.md 
      - Docker主机集群化方案 Docker Swarm: cloud/docker/docker_swarm.md
      - 基于Docker容器DevOps应用方案 企业业务代码发布系统: cloud/docker/docker_devops.md
      - 轻量级或工业级容器管理工具: cloud/docker/docker_container.md     
    - Kubernetes:
      - kubeadm极速部署Kubernetes: cloud/kubernetes.md
      - kubernetes介绍与集群架构: cloud/kubernetes/kubernetes_introduce.md
      - Kubernetes集群部署方式说明: cloud/kubernetes/kubernetes_way.md
      - kubeadm部署单Master节点kubernetes集群: cloud/kubernetes/kubernetes_master.md
      - kubeadm部署高可用kubernetes集群: cloud/kubernetes/kubernetes_hight.md        
      - 使用RKE构建企业生产级Kubernetes集群: cloud/kubernetes/kubernetes_rke.md
      - Kubernetes高可用集群二进制部署（Runtime Docker）一: cloud/kubernetes/kubernetes_hight_bin1.md
      - Kubernetes高可用集群二进制部署（Runtime Docker）二: cloud/kubernetes/kubernetes_hight_bin2.md
      - Kubernetes集群UI及主机资源监控: cloud/kubernetes/kubernetes_ui.md          
      - 使用sealos部署kubernetes集群并实现集群管理: cloud/kubernetes/kubernetes_sealos.md 
      - kubernetes集群命令语法: cloud/kubernetes/kubernetes_cluster.md
      - Kubernetes核心概念: cloud/kubernetes/kubernetes_core.md
      - Kubernetes集群 服务暴露 Nginx Ingress Controller: cloud/kubernetes/kubernetes_nginx_ingress_controller.md
      - Kubernetes集群 服务暴露 Traefik: cloud/kubernetes/kubernetes_traefik.md   
      - Kubernetes配置与密钥管理 ConfigMap&Secret: cloud/kubernetes/kubernetes_configMap_secret.md
      - Kubernetes集群使用容器镜像仓库Harbor: cloud/kubernetes/kubernetes_harbor.md
      - Kubernetes集群安全管理: cloud/kubernetes/kubernetes_safety.md
      - kubernetes持久化存储卷: cloud/kubernetes/kubernetes_storage_volume.md 
      - kubernetes存储解决方案Ceph: cloud/kubernetes/kubernetes_storage_ceph.md
      - Kubernetes集群公共服务: cloud/kubernetes/kubernetes_cluster_serve.md
      - kubernetes集群java项目上云部署: cloud/kubernetes/kubernetes_deploy_java.md
      - kubernetes集群Python项目上云部署: cloud/kubernetes/kubernetes_deploy_python.md
      - Kubernetes集群golang项目上云部署: cloud/kubernetes/kubernetes_deploy_golang.md
      - kubernetes日志收集方案: cloud/kubernetes/kubernetes_logs_collect.md
      - 企业级中间件上云部署 zookeeper: cloud/kubernetes/kubernetes_zookeeper.md
      - kubernetes云原生中间件上云部署 kafka: cloud/kubernetes/kubernetes_kafka.md   
      - rocketmq部署: cloud/kubernetes/kubernetes_rokectmq.md
      - Kubernetes集群包管理解决方案 Helm: cloud/kubernetes/kubernetes_helm.md
      - Kubernetes原生配置管理利器 kustomize: cloud/kubernetes/kubernetes_kustomize.md
      - 源监控: cloud/kubernetes/kubernetes_ui.md 
      - 源监控: cloud/kubernetes/kubernetes_ui.md
      - 源监控: cloud/kubernetes/kubernetes_ui.md
      - 源监控: cloud/kubernetes/kubernetes_ui.md
      - 源监控: cloud/kubernetes/kubernetes_ui.md                                 
  - 微服务:  
      - 分布式锁: micro/fbs-lock.md
      - 微服务设计: micro/design.md
      - 分布式系统与消息的投递: micro/distrimsg.md
      - 基于DDD的微服务设计和开发实战: micro/ddd.md
      - Kafka架构原理: micro/kafka.md
      - Redis Cluster原理: micro/redis_cluster.md
      - 分布式架构: micro/spring-cloud-micro.md
  - 经验分析:
    - DevOps: exp/devops.md   
    - Micro-Service: exp/micro-service.md
    - Raft算法和Gossip协议: exp/raft-gossip.md
    - 集群和负载均衡: exp/cl.md
    - 人工智能: exp/ai.md
    - 代码原则: exp/code-principle.md
    - 如何成为技术大牛: exp/techbig.md
    - 程序员如何技术成长: exp/learnweetout.md    
    - 产品与技术: exp/pt.md
    - 深度学习框架: exp/four_deep_learning.md
    - 在阿里做了5年技术Leader，我总结出这些套路！: exp/tl.md
    - CTO 技能图谱 : exp/cto.md
  - 构架:
    - 构架拆分: framework/split.md 
    - 分布式、高并发、多线程: framework/fgb.md 
    - 如何理解敏捷开发: framework/agility.md 
    - 走向架构师必备的技能: framework/fwork.md
    - 数据中台的思考与总结: framework/data_middle.md
    - 必学的 10 大算法: framework/algorithm-ten.md
  - 情感:
    - 情商: emotion/eq.md
    - 工作心得: emotion/workheard.md
    - 看书: emotion/lookbook.md  
    - 自律: emotion/selfdiscipline.md
    - 为什么活着失败: emotion/livefail.md
    - 情绪管理: emotion/emotion.md
    - 所有的失去，都会以另一种方式归来: emotion/losecome.md
    - 人生有这三种好心态: emotion/threeheart.md
    - 余生，学会一个人走，不管有没有人陪: emotion/onepath.md
    - 往后余生还很精彩，别被熬夜拖垮了: emotion/twopath.md
    - 心态好的人，一辈子都好: emotion/lifetime.md
    
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
      baselevel: 1
      separator: "_"
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://www.googletagmanager.com/gtag/js?id=UA-155084439-1'
  - 'https://www.googletagmanager.com/gtag/js?id=UA-155132293-1'
  - 'js/google.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/burningmyself
    - icon: fontawesome/brands/google 
      link: https://gitee.com/burningmyself

